### PR TITLE
Migrate to ghc-lib-parser

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by neongreen** [comment]
I can also make it so that ghc-lib-parser would only be used on older GHCs, if you want that.

**Comment by mrkkrp** [comment]
Why would I want that?

**Comment by vaibhavsagar** [comment]
I also tried to migrate here: https://github.com/mrkkrp/ghc-syntax-highlighter/pull/10.

**Comment by neongreen** [comment]
Well, you will be able to avoid building ghc-lib-parser if you're using latest GHC.

**Comment by mrkkrp** [comment]
@vaibhavsagar I changed my opinion since then. Also, this PR is more minimal and seems to work fine. Let's give it a go.

**Pull request merged**
