### PR TITLE
[WIP] Use ghc-lib-parser

### PR DESCRIPTION
**Pull request by vaibhavsagar**
This simplifies the implementation significantly without reducing the range of GHC versions that can be supported.

Tests are failing right now but I'm not sure why exactly, and I thought it would be useful to open a PR anyway.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
ping?

**Comment by mrkkrp** [comment]
I thought it's a WIP. I currently have no time or motivation to look into this, as I'm perfectly OK with depending on `ghc` directly. Further, I'm a bit skeptical about the whole `ghc-lib` thing, and its longevity.

**Comment by mrkkrp** [comment]
I'm going to close this. Sorry @vaibhavsagar for not merging this. It would be best to first open an issue and discuss the change.

**Comment by vaibhavsagar** [comment]
No worries, you are right that discussing it first would have been a better approach.

**Pull request closed without merging**
